### ISSUE TITLE
mpdevil v0.3 does not start with error message

### ISSUE THREAD

**Issue by parkmino** [SoongNoonien/mpdevil#1]
Please refer to the followings.
```
Traceback (most recent call last):
  File "/usr/local/bin/mpdevil", line 1605, in <module>
    app = mpdevil()
  File "/usr/local/bin/mpdevil", line 1563, in __init__
    super().__init__(*args, application_id="org.mpdevil", flags=Gio.ApplicationFlags.FLAGS_NONE, **kwargs)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by parkmino** [comment]
FYI, Ubuntu 18.04.3 LTS x86_64

**Comment by SoongNoonien** [comment]
Please try to replace the shebang with something like `#!/usr/bin/python3` cause `#!/usr/bin/python` might point to the wrong python version on Ubuntu 18.04.

**Comment by parkmino** [comment]
Stuck with the following message.

```
Traceback (most recent call last):
  File "/usr/local/bin/mpdevil", line 1569, in do_activate
    self.window = MainWindow(self, self.client, self.settings)
  File "/usr/local/bin/mpdevil", line 1410, in __init__
    self.browser=Browser(self.client, self.settings)
  File "/usr/local/bin/mpdevil", line 430, in __init__
    self.title_list=TrackView(self.client, self.settings)
  File "/usr/local/bin/mpdevil", line 267, in __init__
    self.cover.set_from_pixbuf(Cover(client=self.client, lib_path=self.settings.get_value("paths")[self.settings.get_int("active-profile")], song_file=None).get_pixbuf(self.settings.get_int("track-cover"))) #set to fallback cover
  File "/usr/local/bin/mpdevil", line 78, in get_pixbuf
    self.path = Gtk.IconTheme.get_default().lookup_icon("mpdevil", size, Gtk.IconLookupFlags.FORCE_SVG).get_filename() #fallback cover
AttributeError: 'NoneType' object has no attribute 'get_filename'
```

**Comment by SoongNoonien** [comment]
Ok, I'll have a closer look on this. I'll try to reproduce it. May you send me your exact installation steps?

**Comment by parkmino** [comment]
I downloaded the v0.3 release.

```
$ ./autogen.sh
$ make
$ sudo make install
```

**Comment by SoongNoonien** [comment]
Thanks.

**Comment by SoongNoonien** [comment]
Sadly I wasn't able to reproduce this issue. Could you try to replace in line 78 `Gtk.IconTheme.get_default().lookup_icon("mpdevil", size, Gtk.IconLookupFlags.FORCE_SVG).get_filename()` with `"/usr/local/icons/hicolor/scalable/apps/mpdevil.svg"`?

**Comment by parkmino** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/mpdevil", line 1569, in do_activate
    self.window = MainWindow(self, self.client, self.settings)
  File "/usr/local/bin/mpdevil", line 1410, in __init__
    self.browser=Browser(self.client, self.settings)
  File "/usr/local/bin/mpdevil", line 430, in __init__
    self.title_list=TrackView(self.client, self.settings)
  File "/usr/local/bin/mpdevil", line 267, in __init__
    self.cover.set_from_pixbuf(Cover(client=self.client, lib_path=self.settings.get_value("paths")[self.settings.get_int("active-profile")], song_file=None).get_pixbuf(self.settings.get_int("track-cover"))) #set to fallback cover
  File "/usr/local/bin/mpdevil", line 79, in get_pixbuf
    return GdkPixbuf.Pixbuf.new_from_file_at_size(self.path, size, size)
TypeError: Argument 0 does not allow None as a value
```

**Comment by SoongNoonien** [comment]
I think you have accidentally removed `self.path =` in line 78. Line 78 should be `self.path = "/usr/local/icons/hicolor/scalable/apps/mpdevil.svg"`.

**Comment by parkmino** [comment]
"/usr/local/icons/hicolor/scalable/apps/mpdevil.svg" file is missing.
What is wrong with this?

**Comment by SoongNoonien** [comment]
Ok, this seems to have been the problem in the first place. Something has gone wrong with your installation process. Did you get any errors on install?

**Comment by parkmino** [comment]
"sudo gtk-update-icon-cache -f -t /usr/local/share/icons/hicolor" resolves this issue.
However, my music library is not visible.

**Comment by SoongNoonien** [comment]
Did you set up the right host and port?

**Comment by parkmino** [comment]
Set as default, localhost:6600.
I can see "Server stats", however database does not show.

**Comment by SoongNoonien** [comment]
No, errors on console?

**Comment by parkmino** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/mpdevil", line 359, in refresh
    duration=str(datetime.timedelta(seconds=int(float(song["duration"]))))
KeyError: 'duration'
```

**Comment by SoongNoonien** [comment]
Oh, I'm sorry I forgot to mention mpdevil relies on "AlbumArtist" tag. It is only showing them in the artist column. 
The error message is related to the songs in your current playlist, what filetypes did you add to your playlist?

**Comment by parkmino** [comment]
OK, I don't use tag and it might not fit to me. Good Luck!
FYI, I added mp3.
