### ISSUE TITLE
Empty library: Unknown tag type

### ISSUE THREAD

**Issue by Sjoerdfc** [SoongNoonien/mpdevil#73]
Hi,

I just installed the mpdevil flatpak and tried to connect to my MPD server, but the library stays empty. Also it seems the title of the window is a bit strange. 

![image](https://github.com/SoongNoonien/mpdevil/assets/22343961/6082c756-2615-419b-a69e-955945367672)

I have used multiple different MPD clients, and never had any problems with my library. When I start the flatpak I see the following errors:

```
Gtk-Message: 12:44:06.043: Failed to load module "canberra-gtk-module"

(mpdevil:2): dbind-WARNING **: 12:44:06.047: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Traceback (most recent call last):
  File "/app/bin/mpdevil", line 1695, in _refresh
    artists=self._client.list("albumartistsort", "group", "albumartist")
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 469, in mpd_command
    return wrapper(self, name, args, callback)
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 532, in _execute
    return retval()
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 457, in command_callback
    res = self._wrap_iterator(res)
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 706, in _wrap_iterator
    return list(iterator)
  File "/app/bin/mpdevil", line 668, in _parse_objects
    for key, value in self._parse_pairs(lines):
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 235, in _parse_pairs
    for line in lines:
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 586, in _read_lines
    line = self._read_line()
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 575, in _read_line
    raise CommandError(error)
mpd.base.CommandError: [2@0] {list} Unknown tag type: albumartistsort
Traceback (most recent call last):
  File "/app/bin/mpdevil", line 2325, in _on_playlist_changed
    self._client.restrict_tagtypes("track", "title", "artist", "album", "date")
  File "/app/bin/mpdevil", line 918, in restrict_tagtypes
    self.command_list_end()
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 834, in command_list_end
    return self._wrap_iterator(self._read_command_list())
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 706, in _wrap_iterator
    return list(iterator)
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 692, in _read_command_list
    yield retval()
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 457, in command_callback
    res = self._wrap_iterator(res)
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 706, in _wrap_iterator
    return list(iterator)
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 295, in _parse_list
    for key, value in self._parse_pairs(lines):
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 235, in _parse_pairs
    for line in lines:
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 586, in _read_lines
    line = self._read_line()
  File "/app/lib/python3.10/site-packages/mpd/base.py", line 575, in _read_line
    raise CommandError(error)
mpd.base.CommandError: [2@1] {tagtypes} Unknown tag type
```

I have tried playing different songs when starting mpdevil, I thought maybe there was a problem with the tags of one song, but I can't get it working. The play/pause prev/next buttons do work, but the library stays empty.

**Comment by Sjoerdfc** [comment]
Then the problem is probably that I use Mopidy-MPD, and not an actual MPD server. But I still think it's strange, because every other android and linux client works. MALP, Cantata, Ymuse, MPDroid.

**Comment by SoongNoonien** [comment]
I never tested with Mopidy-MPD and don't plan to do so. I'm using [python-mpd2](https://github.com/Mic92/python-mpd2) to communicate with mpd, this is the actual software talking to the server. So if you want compatibility with Mopidy-MPD you could file a bug report or pull request over there.
